# This test verifies that you can set the securityContext
# for both the Pod and for individual containers in the Pod.

### SECTION:PARAMETERS ###
skipTest: false
### SECTION:VALUES ###
# This is not specific to any particular product
pingdirectory:
  enabled: true
  workload:
    securityContext:
      fsGroup: 1
      runAsGroup: 2
      runAsUser: 3
  container:
    securityContext:
      fsGroup: 4
      runAsGroup: 5
      runAsUser: 6
### SECTION:EXPECTED ###
# Check for Pod-level security context
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: container-securitycontext-pingdirectory
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1
        runAsGroup: 2
        runAsUser: 3
# Check for container-level securityContext
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: container-securitycontext-pingdirectory
spec:
  template:
    spec:
      containers:
      - name: pingdirectory
        securityContext:
          fsGroup: 4
          runAsGroup: 5
          runAsUser: 6
