# This test covers including imagePullSecrets in your global values.

### SECTION:PARAMETERS ###
# If the releaseName parameter is not set, then a default release name
# matching the name of the file (without the extension) will be used.
releaseName: imagepullsecrets
# Set skipTest to true to make the script skip this test
skipTest: false
### SECTION:VALUES ###
global:
  imagePullSecrets:
   - name: myregkeysecretname
pingdirectory:
  enabled: true
### SECTION:EXPECTED ###
# Validate that imagePullSecrets is in the spec for the PD StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: imagepullsecrets-pingdirectory
spec:
  template:
    spec:
      imagePullSecrets:
      - name: myregkeysecretname
---