# This test verifies that you can remove the securityContext
# from the pod spec by setting it to null in your values,
# and that the container securityContext is not set by default.
# This is necessary to deploy the Helm charts on OpenShift

### SECTION:PARAMETERS ###
skipTest: false
### SECTION:VALUES ###
# This is not specific to any particular product
global:
  workload:
    securityContext:
      runAsUser: null
      fsGroup: null
  externalImage:
    pingtoolkit:
      securityContext:
        runAsUser: null

pingaccess-admin:
  enabled: true

pingaccess-engine:
  enabled: true
  
### SECTION:EXPECTED ###
# Validate that the other securityContext fields are set as expected, at
# the pod and container level.
# Check for Pod-level security context
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-securitycontext-pingaccess-engine
spec:
  template:
    spec:
      securityContext:
        runAsGroup: 0
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
# Check for initcontainer-level securityContext
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-securitycontext-pingaccess-engine
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-pingaccess-admin
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
---
### SECTION:UNEXPECTED ###
# Validate that the nulled-out fields override the default values
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-securitycontext-pingaccess-engine
spec:
  template:
    spec:
      securityContext:
        fsGroup: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-securitycontext-pingaccess-engine
spec:
  template:
    spec:
      securityContext:
        runAsUser: 9031
---
# Check for initcontainer-level securityContext
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-securitycontext-pingaccess-engine
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-pingaccess-admin
        securityContext:
          runAsUser: 9031
