# This test is meant to show a simple example of how to format
# a test file for the test_helm_template.py script.

### SECTION:PARAMETERS ###
# The PARAMETERS section is required.
# If the releaseName parameter is not set, then a default release name
# matching the name of the file (without the extension) will be used.
releaseName: saimagepullsecrets
# Set skipTest to true to make the script skip this test
skipTest: false
### SECTION:VALUES ###
# Set typical Helm values here
testFramework:
  enabled: true
  rbac:
    enabled: true
    serviceAccountImagePullSecrets:
    - name: aws-ecr-registry
    - name: dockerhub-secret
### SECTION:EXPECTED ###
# Validate that imagePullSecrets is in the metadata for the test Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: saimagepullsecrets-test-service-account
imagePullSecrets:
  - name: aws-ecr-registry
  - name: dockerhub-secret